[package]
name = "iggy-py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "iggy_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
iggy = "0.0.92"
tokio = { version = "1", features = ["full"] }

